### ISSUE TITLE
NO track?

### ISSUE THREAD

**Issue by Li-Whasaka** [anidh/YOLOv8-TensorRT-ByteTrack#1]

**Comment by anidh** [comment]
Hi @Li-Whasaka ,
The tracker code is only added to the cpp file. You can find the tracker code starting from [here](https://github.com/anidh/YOLOv8-TensorRT-ByteTrack/blob/6ea984a0109247838526f4092064e6adf895c3f7/csrc/detect/end2end/main.cpp#L140)

To run the cpp file you would need to follow the readme from [here](https://github.com/anidh/YOLOv8-TensorRT-ByteTrack/tree/main?tab=readme-ov-file#2-infer-with-c)

Do let me know if you need help with anything else.
